--liquibase formatted sql

--changeset GalushkoID:1
CREATE EXTENSION IF NOT EXISTS dblink;

DO '
BEGIN
PERFORM dblink_exec('''', ''CREATE DATABASE tax_optimizer'');
EXCEPTION WHEN duplicate_database THEN RAISE NOTICE ''%, skipping'', SQLERRM USING ERRCODE = SQLSTATE;
END ';

--changeset GalushkoID:2
drop table if exists test;
create table test
(
    id   int8 generated by default as identity,
    text varchar(255)
)